[build]
  publish = "."
  functions = "netlify/functions"

# Redirect API requests to our serverless function
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200
  force = true